### PR TITLE
Module 4

### PR DESCRIPTION
**Pull request by paulcurren**
Please make sure you are raising this PR against your own repository and not the original. If it says https://github.com/CorndelWithSoftwire in the search bar right now, you are in the wrong place!

Please also don't forget to submit the PR's url to Aptem afterwards (by clicking on the corresponding exercise component, pasting the url in the textbox that appears and then pressing the finish button).

### CODE REVIEW

**Review by CorndelDevOps — COMMENTED** [review]
I don't see ansible files in this PR? This looks like a pull request for module 5, where you added the Dockerfile.
Also, I know you're aware of this, but please avoid committing sensitive values in the repository. It's easy for anyone to view them if they have access to the git history

**Comment by paulcurren** [comment]
> I don't see ansible files in this PR? This looks like a pull request for module 5, where you added the Dockerfile. Also, I know you're aware of this, but please avoid committing sensitive values in the repository. It's easy for anyone to view them if they have access to the git history


Yes, this is just module 4 & 5. Ansible not done yet. 

Yes, I deliberately left the secrets in their - I wanted to test GitGuardian. The secrets are removed in a later merge.

**Comment by CorndelDevOps** [comment]
I'm a bit confused, [Module 4's project exercise](https://project-exercises.devops.corndel.com/exercises/m4_exercise) is about provisioning using Ansible, so I'm not sure what you mean by `Yes, this is just module 4 & 5. Ansible not done yet.`
About secrets, didn't realize you were testing GitGuardian, if you'll remove them all good 👍

**Comment by paulcurren** [comment]
> I'm a bit confused, [Module 4's project exercise](https://project-exercises.devops.corndel.com/exercises/m4_exercise) is about provisioning using Ansible, so I'm not sure what you mean by `Yes, this is just module 4 & 5. Ansible not done yet.` About secrets, didn't realize you were testing GitGuardian, if you'll remove them all good 👍

Apologies - trying to catch up after being off ill over the summer. Yes, it looks like I have skipped the Ansible work and included some of module 5 in this PR. I'm just finishing the final module 5 PR now.

**Comment by BogRad97** [comment]
I've looked at the Dockerfile for exercise 5, and it looks good to me. There are a few things to keep in mind for the stretch goals, but you don't necessarily have to address them:
* The `docker-compose.yml` file contains all 3 services, but they reference the old `.env.X` files
* There aren't instructions in the Readme about running using docker-compose, and that running `build.ps1` first is necessary
* `.gitignore` references `.env.dev` and `.env.prod`, but not `.env`. I'd recommend fixing this as it will possibly save you from committing secrets in future PRs

**Pull request merged**
